from django.urls import path
from . import views
from . import content_views

app_name = 'crp'

urlpatterns = [
    # Authentication
    path('login/', views.custom_login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    
    # Dashboard - CRP roles only (Student, Trainer, Admissions, Admin)
    path('', views.crp_dashboard, name='dashboard'),
    path('student/', views.student_portal_dashboard, name='student_dashboard'),
    path('trainer/', views.trainer_dashboard, name='trainer_dashboard'),
    path('trainer/courses/', views.trainer_courses, name='trainer_courses'),
    path('trainer/courses/<int:course_id>/', views.trainer_course_detail, name='trainer_course_detail'),
    path('trainer/courses/<slug:course_slug>/', views.trainer_course_detail_slug, name='trainer_course_detail_slug'),
    path('trainer/students/', views.trainer_students, name='trainer_students'),
    path('trainer/students/<int:student_id>/', views.trainer_student_detail, name='trainer_student_detail'),
    path('trainer/assessments/', views.trainer_assessments, name='trainer_assessments'),
    path('trainer/assessments/<int:assessment_id>/', views.trainer_assessment_detail, name='trainer_assessment_detail'),
    path('trainer/assessments/create/', views.trainer_assessment_save, name='trainer_assessment_create'),
    path('trainer/assessments/<int:assessment_id>/edit/', views.trainer_assessment_save, name='trainer_assessment_edit'),
    path('trainer/assessments/<int:assessment_id>/publish/', views.trainer_assessment_publish, name='trainer_assessment_publish'),
    path('trainer/assessments/<int:assessment_id>/archive/', views.trainer_assessment_archive, name='trainer_assessment_archive'),
    path('trainer/submissions/<int:submission_id>/', views.trainer_submission_detail, name='trainer_submission_detail'),
    path('trainer/learning-content/', views.trainer_learning_content, name='trainer_learning_content'),
    path('trainer/quizzes/', views.trainer_quizzes, name='trainer_quizzes'),
    path('trainer/quizzes/<int:quiz_id>/', views.trainer_quiz_detail, name='trainer_quiz_detail'),
    path('trainer/announcements/', views.trainer_announcements, name='trainer_announcements'),
    path('trainer/announcements/<int:announcement_id>/delete/', views.trainer_announcement_delete, name='trainer_announcement_delete'),
    path('trainer/schedule/', views.trainer_schedule, name='trainer_schedule'),
    path('trainer/tasks/', views.trainer_task_manager, name='trainer_task_manager'),
    path('trainer/attendance/', views.trainer_attendance, name='trainer_attendance'),
    path('trainer/reports/<slug:report_type>/export/', views.trainer_report_export, name='trainer_report_export'),
    path('trainer/exports/attendance/', views.trainer_report_export, {'report_type': 'attendance'}, name='trainer_export_attendance'),
    path('trainer/exports/tasks/', views.trainer_report_export, {'report_type': 'tasks'}, name='trainer_export_tasks'),
    path('trainer/exports/assessments/', views.trainer_report_export, {'report_type': 'assessments'}, name='trainer_export_assessments'),
    path('trainer/exports/progress/', views.trainer_report_export, {'report_type': 'progress'}, name='trainer_export_progress'),
    path('trainer/exports/cohort-summary/', views.trainer_report_export, {'report_type': 'cohort-summary'}, name='trainer_export_cohort_summary'),
    path('trainer/risk/', views.trainer_risk_workflow, name='trainer_risk_workflow'),
    path('trainer/at-risk/', views.trainer_risk_workflow, name='trainer_at_risk'),
    path('trainer/communications/', views.trainer_communications, name='trainer_communications'),
    path('trainer/messages/', views.trainer_messages, name='trainer_messages'),
    path('trainer/module/<slug:module>/', views.trainer_reference_module, name='trainer_reference_module'),
    path('trainer/content-management/', content_views.content_management, name='trainer_content_management'),
    # Trainer/admin learning-content foundation
    path('content-management/', content_views.content_management, name='content_management'),
    path('content-management/materials/create/', content_views.material_create, name='material_create'),
    path('content-management/materials/<int:material_id>/publish/', content_views.material_publish, name='material_publish'),
    path('content-management/programs/save/', content_views.program_save, name='program_save'),
    path('content-management/programs/<int:program_id>/save/', content_views.program_save, name='program_edit'),
    path('content-management/programs/<int:program_id>/delete/', content_views.program_delete, name='program_delete'),
    path('content-management/cohorts/save/', content_views.cohort_save, name='cohort_save'),
    path('content-management/cohorts/<int:cohort_id>/save/', content_views.cohort_save, name='cohort_edit'),
    path('content-management/cohorts/<int:cohort_id>/delete/', content_views.cohort_delete, name='cohort_delete'),
    path('content-management/weeks/save/', content_views.week_save, name='week_save'),
    path('content-management/weeks/<int:week_id>/save/', content_views.week_save, name='week_edit'),
    path('content-management/weeks/<int:week_id>/delete/', content_views.week_delete, name='week_delete'),
    path('content-management/quizzes/create/', content_views.quiz_create, name='quiz_create'),
    path('content-management/quizzes/<int:quiz_id>/publish/', content_views.quiz_publish, name='quiz_publish'),
    path('content-management/quizzes/<int:quiz_id>/questions/create/', content_views.quiz_question_create, name='quiz_question_create'),
    path('content-management/quizzes/<int:quiz_id>/delete/', content_views.quiz_delete, name='quiz_delete'),
    path('content-management/questions/<int:question_id>/delete/', content_views.quiz_question_delete, name='quiz_question_delete'),
    path('content-management/quizzes/<int:quiz_id>/questions/save/', content_views.quiz_question_save, name='quiz_question_save'),
    path('content-management/questions/<int:question_id>/save/', content_views.quiz_question_save, name='quiz_question_edit'),
    path('content-management/options/<int:option_id>/delete/', content_views.quiz_option_delete, name='quiz_option_delete'),
    path('content-management/questions/<int:question_id>/options/save/', content_views.quiz_option_save, name='quiz_option_save'),
    path('content-management/options/<int:option_id>/save/', content_views.quiz_option_save, name='quiz_option_edit'),
    path('content-management/assessments/create/', content_views.assessment_create, name='assessment_create'),
    path('content-management/assessments/<int:assessment_id>/publish/', content_views.assessment_publish, name='assessment_publish'),
    path('content-management/assessments/<int:assessment_id>/archive/', content_views.assessment_archive, name='assessment_archive'),
    path('content-management/assessments/<int:assessment_id>/release-results/', content_views.assessment_release_results, name='assessment_release_results'),
    path('content-management/assessments/<int:assessment_id>/rubric/', content_views.rubric_save, name='rubric_save'),
    path('content-management/assessments/<int:assessment_id>/rubric/criteria/save/', content_views.rubric_criterion_save, name='rubric_criterion_save'),
    path('content-management/rubric-criteria/<int:criterion_id>/save/', content_views.rubric_criterion_save, name='rubric_criterion_edit'),
    path('content-management/rubric-criteria/<int:criterion_id>/delete/', content_views.rubric_criterion_delete, name='rubric_criterion_delete'),
    path('content-management/submissions/<int:submission_id>/mark/', content_views.submission_mark, name='submission_mark'),
    path('admissions/', views.admissions_dashboard, name='admissions_dashboard'),
    path('admissions-finance/', views.admissions_finance_dashboard, name='admissions_finance_dashboard'),
    path('admissions-finance/applications/', views.admissions_applications, name='admissions_applications'),
    path('admissions-finance/applications/<int:registration_id>/', views.admissions_application_detail, name='admissions_application_detail'),
    path('admissions-finance/applications/<int:registration_id>/transition/', views.admissions_application_transition, name='admissions_application_transition'),
    path('admissions-finance/applications/<int:registration_id>/documents/request/', views.application_document_request, name='application_document_request'),
    path('admissions-finance/applications/<int:registration_id>/documents/<int:document_id>/', views.application_document_detail, name='application_document_detail'),
    path('admissions-finance/applications/<int:registration_id>/documents/<int:document_id>/verify/', views.application_document_verify, name='application_document_verify'),
    path('admissions-finance/applications/<int:registration_id>/contracts/create/', views.application_contract_create, name='application_contract_create'),
    path('admissions-finance/applications/<int:registration_id>/contracts/<int:contract_id>/', views.application_contract_detail, name='application_contract_detail'),
    path('admissions-finance/applications/<int:registration_id>/contracts/<int:contract_id>/send/', views.application_contract_send, name='application_contract_send'),
    path('admissions-finance/applications/<int:registration_id>/contracts/<int:contract_id>/accept/', views.application_contract_accept, name='application_contract_accept'),
    path('admissions-finance/contracts/', views.admissions_contracts, name='admissions_contracts'),
    path('admissions-finance/invoices/', views.finance_invoices, name='finance_invoices'),
    path('admissions-finance/invoices/<int:invoice_id>/', views.finance_invoice_detail, name='finance_invoice_detail'),
    path('admissions-finance/invoices/<int:invoice_id>/payment/', views.record_payment, name='record_payment'),
    path('admissions-finance/invoices/<int:invoice_id>/clearance/', views.finance_clearance, name='finance_clearance'),
    path('admissions-finance/revenue/', views.revenue_analytics, name='revenue_analytics'),
    path('admissions-finance/payment-risk/', views.payment_risk, name='payment_risk'),
    path('admin/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/jobs/', views.admin_job_sources, name='admin_job_sources'),
    path('admin/courses/', views.admin_courses, name='admin_courses'),
    path('admin/courses/<int:course_id>/', views.admin_course_detail, name='admin_course_detail'),
    path('admin/courses/<int:course_id>/<slug:action>/', views.admin_course_toggle, name='admin_course_toggle'),
    path('admin/enrollments/', views.admin_enrollments, name='admin_enrollments'),
    path('admin/enrollments/<int:registration_id>/', views.admin_enrollment_detail, name='admin_enrollment_detail'),
    path('admin/enrollments/<int:registration_id>/<slug:action>/', views.admin_enrollment_action, name='admin_enrollment_action'),
    path('admin/legacy-mapping/', views.admin_legacy_mapping, name='admin_legacy_mapping'),
    path('admin/trainers/', views.admin_trainers, name='admin_trainers'),
    path('admin/academic/<slug:module>/', views.admin_academic_module, name='admin_academic_module'),
    path('admin/operations/<slug:module>/', views.admin_operations_module, name='admin_operations_module'),
    path('support/tickets/', views.support_tickets, name='support_tickets'),
    path('admin/system/<slug:module>/', views.admin_system_module, name='admin_system_module'),
    
    # Student Portal - Phase 2A
    path('student/portal/', views.student_portal_dashboard, name='student_portal'),
    path('student/courses/<int:course_id>/', views.student_course_home, name='student_course_home'),
    path('student/courses/<int:course_id>/weeks/<int:week_id>/', views.student_course_week, name='student_course_week'),
    path('student/courses/<int:course_id>/request/', views.request_course_enrollment, name='request_course_enrollment'),
    path('student/learning/', views.student_learning_hub, name='student_learning'),
    path('student/quiz/', views.student_quiz_list, name='student_quiz'),
    path('student/quiz/<int:quiz_id>/', views.student_quiz_take, name='student_quiz_take'),
    path('student/assessments/', views.student_assessments, name='student_assessments'),
    path('student/assessments/<int:assessment_id>/', views.student_assessment_detail, name='student_assessment_detail'),
    path('student/assessments/<int:assessment_id>/submit/', views.student_assessment_submit, name='student_assessment_submit'),
    path('student/api/toggle-material/', views.toggle_material_progress, name='toggle_material_progress'),
    path('student/api/toggle-task/', views.toggle_task_completion, name='toggle_task_completion'),

    # Student Productivity - Phase 2C
    path('student/tasks/', views.student_tasks, name='student_tasks'),
    path('student/tasks/<int:task_id>/edit/', views.student_task_edit, name='student_task_edit'),
    path('student/tasks/<int:task_id>/delete/', views.student_task_delete, name='student_task_delete'),
    path('student/messages/', views.student_messages, name='student_messages'),
    path('student/messages/<int:thread_id>/', views.student_message_thread, name='student_message_thread'),
    path('student/messages/<int:thread_id>/send/', views.student_message_send, name='student_message_send'),
    path('student/notifications/', views.notifications, name='student_notifications'),
    path('notifications/', views.notifications, name='portal_notifications'),
    path('student/notes/', views.student_notes, name='student_notes'),
    path('student/calendar/', views.student_calendar, name='student_calendar'),
    path('student/calendar/<int:event_id>/edit/', views.student_calendar_event_edit, name='student_calendar_event_edit'),
    path('student/live-sessions/', views.student_live_sessions, name='student_live_sessions'),
    path('student/attendance/', views.student_attendance, name='student_attendance'),
    path('student/announcements/', views.student_announcements, name='student_announcements'),
    path('student/requests/', views.student_requests, name='student_requests'),
    path('student/groups/', views.student_groups, name='student_groups'),
    path('student/groups/<int:group_id>/', views.student_group_detail, name='student_group_detail'),
    path('student/groups/<int:group_id>/join/', views.student_group_join, name='student_group_join'),
    path('student/groups/<int:group_id>/leave/', views.student_group_leave, name='student_group_leave'),

    # Student Community & Settings - Phase 2D
    path('student/community/', views.student_community, name='student_community'),
    path('student/community/<int:post_id>/', views.student_community_post_detail, name='student_community_post_detail'),
    path('student/community/<int:post_id>/edit/', views.student_community_post_edit, name='student_community_post_edit'),
    path('student/community/<int:post_id>/delete/', views.student_community_post_delete, name='student_community_post_delete'),
    path('student/community/<int:post_id>/like/', views.student_community_post_like, name='student_community_post_like'),
    path('student/settings/', views.student_settings, name='student_settings'),
    path('student/settings/<int:student_id>/', views.student_settings_by_id, name='student_settings_by_id'),
    
    # Student Portal - Phase 2B: Career Section
    path('student/jobs/', views.student_jobs, name='student_jobs'),
    path('student/jobs/recommendations/', views.student_jobs, {'recommendations': True}, name='student_job_recommendations'),
    path('student/jobs/applications/', views.student_job_applications, name='student_job_applications'),
    path('student/jobs/saved/', views.student_job_applications, {'status': 'saved'}, name='student_saved_jobs'),
    path('student/jobs/preferences/', views.student_job_preferences, name='student_job_preferences'),
    path('student/jobs/<slug:job_slug>/', views.student_job_detail, name='student_job_detail'),
    path('student/jobs/<int:job_id>/save/', views.student_save_job, name='student_save_job'),
    path('student/jobs/<int:job_id>/apply/', views.student_apply_job, name='student_apply_job'),
    path('student/resume/', views.student_resume, name='student_resume'),
    path('student/resume/export/', views.student_export_resume, name='student_export_resume'),
    path('student/resume/tailor/<int:job_id>/', views.student_tailor_resume, name='student_tailor_resume'),
    path('student/resume/tailored/<int:tailored_id>/', views.student_tailored_resume, name='student_tailored_resume'),
    path('student/resume/tailored/<int:tailored_id>/export/', views.student_export_tailored_resume, name='student_export_tailored_resume'),
    path('student/resume/tailored/<int:tailored_id>/export/pdf/', views.student_export_tailored_resume_pdf, name='student_export_tailored_resume_pdf'),
    path('student/resume/api/skill/add/', views.resume_add_skill, name='resume_add_skill'),
    path('student/resume/api/skill/remove/', views.resume_remove_skill, name='resume_remove_skill'),
    path('student/resume/api/save/', views.resume_autosave, name='resume_autosave'),
    path('student/resume/api/experience/add/', views.resume_add_experience, name='resume_add_experience'),
    path('student/resume/api/experience/<int:exp_id>/edit/', views.resume_edit_experience, name='resume_edit_experience'),
    path('student/resume/api/experience/<int:exp_id>/delete/', views.resume_delete_experience, name='resume_delete_experience'),
    path('student/resume/api/experience/<int:exp_id>/bullet/add/', views.resume_add_bullet, name='resume_add_bullet'),
    path('student/resume/api/experience/<int:exp_id>/bullet/<int:bullet_index>/edit/', views.resume_edit_bullet, name='resume_edit_bullet'),
    path('student/resume/api/experience/<int:exp_id>/bullet/<int:bullet_index>/delete/', views.resume_delete_bullet, name='resume_delete_bullet'),
    path('student/resume/api/education/add/', views.resume_add_education, name='resume_add_education'),
    path('student/resume/api/education/<int:edu_id>/edit/', views.resume_edit_education, name='resume_edit_education'),
    path('student/resume/api/education/<int:edu_id>/delete/', views.resume_delete_education, name='resume_delete_education'),
    path('student/resume/api/re-run-ai/', views.resume_rerun_ai, name='resume_rerun_ai'),
    path('student/interview/', views.student_interview, name='student_interview'),
    path('student/interview/<int:set_id>/start/', views.student_start_interview, name='student_start_interview'),
    path('student/interview/<int:attempt_id>/', views.student_interview_session, name='student_interview_session'),
    path('student/linkedin/', views.student_linkedin, name='student_linkedin'),
    path('student/achievements/', views.student_achievements, name='student_achievements'),
    
    # Courses
    path('courses/', views.CourseListView.as_view(), name='course_list'),
    path('courses/<int:pk>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('courses/create/', views.CourseCreateView.as_view(), name='course_create'),
    path('courses/<int:pk>/update/', views.CourseUpdateView.as_view(), name='course_update'),
    path('courses/<int:course_id>/register/', views.register_for_course, name='register_for_course'),
    
    # Registrations
    path('registrations/', views.my_registrations, name='my_registrations'),
    path('registrations/<int:registration_id>/approve/', views.approve_registration, name='approve_registration'),
    path('registrations/<int:registration_id>/reject/', views.reject_registration, name='reject_registration'),
    path('registrations/<int:registration_id>/withdraw/', views.withdraw_registration, name='withdraw_registration'),
    path('registrations/<int:registration_id>/pdf/', views.download_registration_pdf, name='download_registration_pdf'),
    
    # Schedules
    path('schedules/', views.ScheduleListView.as_view(), name='schedule_list'),
    
    # Announcements
    path('announcements/', views.AnnouncementListView.as_view(), name='announcement_list'),
    path('announcements/<int:pk>/', views.AnnouncementDetailView.as_view(), name='announcement_detail'),
    path('announcements/create/', views.AnnouncementCreateView.as_view(), name='announcement_create'),
    
    # Image Uploads
    path('images/', views.image_upload_list, name='image_upload_list'),
    path('images/upload/', views.image_upload_create, name='image_upload_create'),
    path('images/<int:pk>/', views.image_upload_detail, name='image_upload_detail'),
    path('images/<int:pk>/delete/', views.image_upload_delete, name='image_upload_delete'),
    
    # Exports
    path('export/courses/', views.export_courses, name='export_courses'),
]
