# Generated by Django 5.2.4 on 2026-09-03 06:29

import crp_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0002_campaign_campaignmetrics_financeprofile_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Course cover image', null=True, upload_to=crp_app.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, help_text='Department logo', null=True, upload_to=crp_app.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional biography'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Instructor profile photo', null=True, upload_to=crp_app.models.get_image_upload_path),
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=crp_app.models.get_image_upload_path)),
                ('category', models.CharField(choices=[('course', 'Course Image'), ('instructor', 'Instructor Photo'), ('department', 'Department Logo'), ('announcement', 'Announcement Image'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=50)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='crp_app_upl_categor_136888_idx'), models.Index(fields=['uploaded_by'], name='crp_app_upl_uploade_b52843_idx')],
            },
        ),
    ]
