# Generated by Django 5.2.4 on 2026-09-03 09:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0003_course_image_department_logo_instructor_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('topics', models.JSONField(default=list, help_text='List of topic tags')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('current', 'Current'), ('done', 'Done')], default='locked', max_length=20)),
                ('unlocks_after_week', models.IntegerField(blank=True, help_text='Week number that must be completed first', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('slides', 'Slide Deck'), ('pdf', 'PDF Document'), ('video', 'Video Recording'), ('workbook', 'Workbook'), ('link', 'External Link'), ('other', 'Other')], max_length=20)),
                ('file_url', models.URLField(blank=True, help_text='URL to the material file')),
                ('file_size', models.CharField(blank=True, help_text="e.g., '4.1 MB', '52 min'", max_length=50)),
                ('duration', models.CharField(blank=True, help_text="For videos, e.g., '52 min'", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order within the week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='crp_app.learningweek')),
            ],
            options={
                'ordering': ['week', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('assignment', 'Assignment'), ('project', 'Project'), ('presentation', 'Presentation'), ('exam', 'Exam'), ('quiz', 'Quiz')], max_length=20)),
                ('description', models.TextField()),
                ('course_code', models.CharField(help_text="e.g., 'CRP101'", max_length=20)),
                ('max_marks', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('weight_percentage', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('due_date', models.DateTimeField()),
                ('accepted_formats', models.JSONField(default=list, help_text='List of accepted file formats')),
                ('turnitin_enabled', models.BooleanField(default=False, help_text='Enable Turnitin plagiarism check')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='crp_app.learningweek')),
            ],
            options={
                'ordering': ['week', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('question_count', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('time_limit_minutes', models.IntegerField(default=30, help_text='Time limit in minutes')),
                ('passing_score', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_adaptive', models.BooleanField(default=True, help_text='Difficulty adapts to answers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='crp_app.learningweek')),
            ],
            options={
                'ordering': ['week'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='crp_app.quiz')),
            ],
            options={
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Display order (A, B, C, D)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='crp_app.quizquestion')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='crp_app.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField(default=0)),
                ('level_descriptions', models.JSONField(default=dict, help_text='Descriptions for each achievement level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='crp_app.rubric')),
            ],
            options={
                'ordering': ['rubric', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('specialisation', models.CharField(choices=[('ai', 'Artificial Intelligence'), ('cybersecurity', 'Cybersecurity'), ('data_analytics', 'Data Analytics'), ('project_management', 'Project Management'), ('information_systems', 'Information Systems')], default='ai', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('cohort', models.CharField(help_text='e.g., Q3 2026', max_length=50)),
                ('program_start_date', models.DateField()),
                ('program_end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('attendance_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('employability_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_streak', models.IntegerField(default=0, help_text='Current day streak of activity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_spent_minutes', models.IntegerField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict, help_text='Store question answers and correctness')),
                ('is_passed', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='crp_app.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='crp_app.student')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='crp_app.learningmaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_progress', to='crp_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('class', 'Class'), ('workshop', 'Workshop'), ('deadline', 'Deadline'), ('appointment', 'Appointment'), ('coaching', 'Career Coaching'), ('interview', 'Mock Interview'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crp_app.student')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('marked', 'Marked'), ('returned', 'Returned')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('marks_awarded', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True)),
                ('turnitin_similarity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_detection_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('marker_comments', models.JSONField(default=dict, help_text='Comments per rubric criterion')),
                ('is_late', models.BooleanField(default=False)),
                ('extension_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='crp_app.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='crp_app.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, help_text="e.g., 'Personal', 'Academic', 'Career'", max_length=50)),
                ('created_by', models.CharField(default='Self', help_text='Who created the task', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crp_app.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text="e.g., 'PDF', 'Word', 'Video'", max_length=50)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crp_app.assessmentsubmission')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['week', 'due_date'], name='crp_app_ass_week_id_7a62f4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='crp_app_stu_student_52fe2f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['cohort'], name='crp_app_stu_cohort_bfb216_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='crp_app_stu_status_1ea0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'quiz'], name='crp_app_qui_student_0327f8_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', '-started_at'], name='crp_app_qui_student_6545a3_idx'),
        ),
        migrations.AddIndex(
            model_name='materialprogress',
            index=models.Index(fields=['student', 'completed'], name='crp_app_mat_student_a56e61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialprogress',
            unique_together={('student', 'material')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['student', 'date'], name='crp_app_eve_student_49d5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubmission',
            index=models.Index(fields=['student', 'status'], name='crp_app_ass_student_2a8b08_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubmission',
            index=models.Index(fields=['assessment', 'status'], name='crp_app_ass_assessm_62eb27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsubmission',
            unique_together={('student', 'assessment')},
        ),
        migrations.AddIndex(
            model_name='studenttask',
            index=models.Index(fields=['student', 'completed'], name='crp_app_stu_student_e545d1_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttask',
            index=models.Index(fields=['student', 'due_date'], name='crp_app_stu_student_db4422_idx'),
        ),
    ]
