# Generated by Django 5.2.4 on 2026-09-03 15:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0004_learningweek_learningmaterial_assessment_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon identifier', max_length=50)),
                ('color', models.CharField(default='#0f7a5a', max_length=20)),
                ('week_earned', models.IntegerField(blank=True, help_text='Week when badge can be earned', null=True)),
                ('points', models.IntegerField(default=10, help_text='Points awarded for this badge')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['week_earned', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('situational', 'Situational'), ('mixed', 'Mixed')], default='mixed', max_length=100)),
                ('question_count', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('time_limit_minutes', models.IntegerField(default=15, help_text='Total time for the interview')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('hint', models.TextField(blank=True, help_text='Coach hint for students')),
                ('target_word_count', models.IntegerField(default=150, help_text='Target word count for answer')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='crp_app.interviewset')),
            ],
            options={
                'ordering': ['interview_set', 'order'],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(help_text="e.g., '$75K–$95K'", max_length=100)),
                ('salary_min', models.IntegerField(blank=True, help_text='Minimum salary in thousands', null=True)),
                ('salary_max', models.IntegerField(blank=True, help_text='Maximum salary in thousands', null=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=50)),
                ('fields', models.JSONField(default=list, help_text='List of field categories')),
                ('skills', models.JSONField(default=list, help_text='List of required skills')),
                ('description', models.TextField()),
                ('match_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('posted_date', models.DateField()),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-match_percentage', '-posted_date'],
                'indexes': [models.Index(fields=['fields'], name='crp_app_job_fields_724801_idx'), models.Index(fields=['match_percentage'], name='crp_app_job_match_p_b6c571_idx'), models.Index(fields=['posted_date'], name='crp_app_job_posted__d2dce5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list, help_text='List of skills')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_location', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('ai_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_feedback', models.JSONField(default=dict, help_text='AI review feedback')),
                ('completeness_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='crp_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('gpa', models.CharField(blank=True, max_length=10)),
                ('details', models.CharField(blank=True, help_text="e.g., 'Honours', 'Dean's List'", max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='crp_app.resume')),
            ],
            options={
                'ordering': ['-is_current', '-end_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('bullets', models.JSONField(default=list, help_text='List of achievement bullets')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='crp_app.resume')),
            ],
            options={
                'ordering': ['-is_current', '-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, help_text='Current consecutive days')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest consecutive days')),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('streak_history', models.JSONField(default=list, help_text='List of daily activity records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='crp_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_badges', to='crp_app.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='crp_app.student')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('time_spent_minutes', models.IntegerField(blank=True, null=True)),
                ('answers', models.JSONField(default=list, help_text='List of answer objects with ratings')),
                ('feedback', models.JSONField(default=list, help_text='AI coach feedback')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_attempts', to='crp_app.student')),
                ('interview_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='crp_app.interviewset')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', '-started_at'], name='crp_app_int_student_2757c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('interview', 'Interview'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='saved', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='crp_app.student')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='crp_app.joblisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='crp_app_job_student_b808b9_idx')],
                'unique_together': {('student', 'job')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(help_text="e.g., 'Q3 2026'", max_length=50)),
                ('total_points', models.IntegerField(default=0)),
                ('quiz_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('badges_count', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='crp_app.student')),
            ],
            options={
                'ordering': ['cohort', 'rank'],
                'indexes': [models.Index(fields=['cohort', 'rank'], name='crp_app_lea_cohort_00647d_idx')],
                'unique_together': {('student', 'cohort')},
            },
        ),
        migrations.CreateModel(
            name='LinkedInProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeness_items', models.JSONField(default=dict, help_text='Dictionary of completion items with boolean status')),
                ('completeness_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('about', models.TextField(blank=True)),
                ('forecast_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=20)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_profile', to='crp_app.student')),
            ],
            options={
                'indexes': [models.Index(fields=['completeness_score'], name='crp_app_lin_complet_890345_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['completeness_score'], name='crp_app_res_complet_fffed3_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['current_streak'], name='crp_app_str_current_c81361_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbadge',
            index=models.Index(fields=['student', '-earned_at'], name='crp_app_stu_student_dd5af6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentbadge',
            unique_together={('student', 'badge')},
        ),
    ]
