# Generated by Django 5.2.4 on 2026-09-15 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0009_applicationdocument_applicationcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentWeekProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['week__week_number'],
            },
        ),
        migrations.RenameIndex(
            model_name='applicationdocument',
            new_name='crp_app_app_registr_6bb562_idx',
            old_name='crp_app_applic_registr_5da7ed_idx',
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='required_file_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessment',
            name='required_submission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='results_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='question_ids',
            field=models.JSONField(default=list, help_text='Question snapshot used for this attempt'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='crp_app.cohort'),
        ),
        migrations.AddField(
            model_name='student',
            name='cohort_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='crp_app.cohort'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='crp_app.program'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='crp_app.program'),
        ),
        migrations.AddField(
            model_name='learningweek',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_weeks', to='crp_app.program'),
        ),
        migrations.AddField(
            model_name='studentweekprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_progress', to='crp_app.student'),
        ),
        migrations.AddField(
            model_name='studentweekprogress',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='crp_app.learningweek'),
        ),
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together={('program', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='studentweekprogress',
            unique_together={('student', 'week')},
        ),
    ]
