# Generated by Django 5.2.4 on 2026-09-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0010_cohort_program_studentweekprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningweek',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='option_snapshots',
            field=models.JSONField(default=dict, help_text='Exact option text/order/correctness used for this attempt'),
        ),
    ]
