# Generated by Django 5.2.4 on 2026-09-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0013_content_management_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='crp_app.cohort'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='crp_app.program'),
        ),
    ]
