# Generated by Django 5.2.4 on 2026-09-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0014_announcement_cohort_announcement_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
