# Generated by Django 5.2.4 on 2026-09-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0015_assessment_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
