# Generated by Django 5.2.4 on 2026-09-17 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def link_legacy_learning_data(apps, schema_editor):
    Course = apps.get_model('crp_app', 'Course')
    Assessment = apps.get_model('crp_app', 'Assessment')
    LearningWeek = apps.get_model('crp_app', 'LearningWeek')
    courses = {course.code: course for course in Course.objects.all()}
    for assessment in Assessment.objects.filter(course__isnull=True):
        course = courses.get(assessment.course_code)
        if course:
            assessment.course_id = course.id
            assessment.save(update_fields=['course'])
            if assessment.week.course_id is None:
                assessment.week.course_id = course.id
                assessment.week.save(update_fields=['course'])


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0017_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='crp_app.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(blank=True, help_text='Trainers assigned to this course.', related_name='assigned_courses', to='crp_app.instructor'),
        ),
        migrations.AddField(
            model_name='learningweek',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_weeks', to='crp_app.course'),
        ),
        migrations.AlterField(
            model_name='learningweek',
            name='week_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.RunPython(link_legacy_learning_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='learningweek',
            constraint=models.UniqueConstraint(fields=('course', 'week_number'), name='unique_course_learning_week'),
        ),
    ]
