# Generated by Django 5.2.4 on 2026-09-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0018_assessment_course_course_trainers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
