# Generated by Django 5.2.4 on 2026-09-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0021_alter_studentnote_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded PDF or video file', null=True, upload_to='learning_materials/%Y/%m/'),
        ),
    ]
