# Generated by Django 5.2.4 on 2026-09-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0023_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension_requests', to='crp_app.assessment'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='open', max_length=20),
        ),
    ]
