# Generated by Django 5.2.4 on 2026-09-19 09:13

from django.db import migrations, models
from django.utils.text import slugify


def populate_course_slugs(apps, schema_editor):
    Course = apps.get_model('crp_app', 'Course')
    used_slugs = set()
    for course in Course.objects.order_by('id'):
        base_slug = slugify(course.name) or slugify(course.code)
        candidate = base_slug
        if candidate in used_slugs:
            candidate = f'{base_slug}-{slugify(course.code)}'
        while candidate in used_slugs:
            candidate = f'{candidate}-{course.pk}'
        course.slug = candidate
        course.save(update_fields=['slug'])
        used_slugs.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0025_successstory_supportticket_supportticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.RunPython(populate_course_slugs, migrations.RunPython.noop),
    ]
