# Generated by Django 5.2.4 on 2026-09-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0027_global_job_aggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsource',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobsource',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsource',
            name='sync_interval_hours',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='jobsyncrun',
            name='jobs_expired',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobsyncrun',
            name='jobs_stale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
