# Generated by Django 5.2.4 on 2026-09-26 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0028_joblisting_expires_at_joblisting_last_seen_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailoredResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('analysis', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_resumes', to='crp_app.joblisting')),
                ('source_resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tailored_versions', to='crp_app.resume')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_resumes', to='crp_app.student')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student', 'job'], name='crp_app_tai_student_15ab35_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'job', 'source_resume', 'version'), name='unique_tailored_resume_version')],
            },
        ),
    ]
