# Generated by Django 5.2.4 on 2026-09-27 08:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_app', '0032_rubric_is_published_rubric_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='marks_awarded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='SubmissionRubricResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_marks', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_results', to='crp_app.rubriccriterion')),
                ('performance_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission_results', to='crp_app.rubricperformancelevel')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_results', to='crp_app.assessmentsubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('submission', 'criterion'), name='unique_submission_rubric_criterion')],
            },
        ),
    ]
